# Generated by Django 4.2.4 on 2024-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransportinvoice',
            name='referance_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference No'),
        ),
        migrations.AlterField(
            model_name='transportinvoice',
            name='referance_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference No'),
        ),
    ]
