# Generated by Django 4.2.4 on 2024-07-11 09:58

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name_en', models.CharField(max_length=64, verbose_name='Account Name English')),
                ('account_name_ar', models.CharField(max_length=64, verbose_name='Account Name Arabic')),
                ('account_type', models.CharField(choices=[('A', 'Asset'), ('L', 'Liability'), ('E', 'Equity'), ('R', 'Revenue'), ('X', 'Expense')], max_length=1, verbose_name='Account Type')),
                ('account_number', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='Account Number')),
                ('allow_child_accounts', models.BooleanField(default=False, verbose_name='Allow Child Accounts')),
                ('allow_edit', models.BooleanField(default=True, verbose_name='Allow Edit')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'permissions': [('print_account_statement', 'Can Print Account Statement'), ('print_account_receipt_voucher', 'Can Print Account Receipt Voucher'), ('can_view_agent_account', 'Can View Agent Account'), ('can_view_transport_company_account', 'Can View Transport Company Account'), ('can_view_internal_account', 'Can View Internal Account'), ('can_view_accounts_tree', 'Can View Accounts Tree')],
            },
        ),
        migrations.CreateModel(
            name='AccountSettlementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('reference_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number')),
                ('payment_method', models.CharField(blank=True, choices=[('settlement', 'Settlement')], default='settlement', max_length=16, null=True, verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Account Settlement Credit',
                'verbose_name_plural': 'Account Settlement Credits',
            },
        ),
        migrations.CreateModel(
            name='AccountSettlementDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('reference_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number')),
                ('payment_method', models.CharField(blank=True, choices=[('settlement', 'Settlement')], default='settlement', max_length=16, null=True, verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Account Settlement Debit',
                'verbose_name_plural': 'Account Settlement Debits',
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
            },
        ),
        migrations.CreateModel(
            name='HistoricalJournalEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Date')),
                ('description_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description English')),
                ('description_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Arabic')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Credit')),
                ('entry_for', models.CharField(max_length=16, null=True, verbose_name='Entry For')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Journal Entry',
                'verbose_name_plural': 'historical Journal Entries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentVoucher',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('paid_to_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Paid To')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('reference_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Payment Voucher',
                'verbose_name_plural': 'historical Payment Vouchers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReceiptVoucher',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('collected_from_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Collected From')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('reference_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Receipt Voucher',
                'verbose_name_plural': 'historical Receipt Vouchers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Date')),
                ('description_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description English')),
                ('description_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Arabic')),
                ('reference_no', models.CharField(blank=True, max_length=256, null=True, verbose_name='Reference')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('description_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description English')),
                ('description_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Arabic')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Credit')),
                ('entry_for', models.CharField(max_length=16, null=True, verbose_name='Entry For')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('paid_to_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Paid To')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('reference_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment Voucher',
                'verbose_name_plural': 'Payment Vouchers',
            },
        ),
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('collected_from_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Collected From')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('reference_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Receipt Voucher',
                'verbose_name_plural': 'Receipt Vouchers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('description_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description English')),
                ('description_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Arabic')),
                ('reference_no', models.CharField(blank=True, max_length=256, null=True, verbose_name='Reference')),
            ],
        ),
    ]
