# Generated by Django 4.2.4 on 2024-06-29 14:43

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name_en', models.CharField(max_length=64, verbose_name='اسم الحساب  بالانجليزي')),
                ('account_name_ar', models.CharField(max_length=64, verbose_name='اسم الحساب بالعربي')),
                ('account_type', models.CharField(choices=[('A', 'Asset'), ('L', 'Liability'), ('E', 'Equity'), ('R', 'Revenue'), ('X', 'Expense')], max_length=1, verbose_name='نوع الحساب')),
                ('account_number', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='Account Number')),
                ('allow_child_accounts', models.BooleanField(default=False, verbose_name='السماح بحسابات الفرعي')),
                ('allow_edit', models.BooleanField(default=True, verbose_name='Allow Edit')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'permissions': [('print_account_statement', 'Can Print Account Statement'), ('print_account_receipt_voucher', 'Can Print Account Receipt Voucher'), ('can_view_agent_account', 'Can View Agent Account'), ('can_view_transport_company_account', 'Can View Transport Company Account'), ('can_view_internal_account', 'Can View Internal Account'), ('can_view_accounts_tree', 'Can View Accounts Tree')],
            },
        ),
        migrations.CreateModel(
            name='AccountSettlementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=256, verbose_name='البيان')),
                ('referance_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Referance Number')),
                ('payment_method', models.CharField(blank=True, choices=[('settlement', 'Settlement')], default='settlement', max_length=16, null=True, verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'تسوية حساب دائن',
                'verbose_name_plural': 'تسوية حساب دائن',
            },
        ),
        migrations.CreateModel(
            name='AccountSettlementDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=256, verbose_name='البيان')),
                ('referance_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Referance Number')),
                ('payment_method', models.CharField(blank=True, choices=[('settlement', 'Settlement')], default='settlement', max_length=16, null=True, verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'تسوية حساب مدين',
                'verbose_name_plural': 'تسوية حساب مدين',
            },
        ),
        migrations.CreateModel(
            name='DebitVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=256, verbose_name='البيان')),
                ('referance_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Referance Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'سند صرف',
                'verbose_name_plural': 'سندات صرف',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='التاريخ')),
                ('description_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description English')),
                ('description_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Arabic')),
                ('reference_no', models.CharField(blank=True, max_length=256, null=True, verbose_name='Reference')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='التاريخ')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='دائن')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
            },
        ),
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=256, verbose_name='البيان')),
                ('referance_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Referance Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'Receipt Vouchers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='التاريخ')),
                ('description_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description English')),
                ('description_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Arabic')),
                ('reference_no', models.CharField(blank=True, max_length=256, null=True, verbose_name='Reference')),
            ],
        ),
    ]
