# Generated by Django 4.2.4 on 2024-07-11 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.financialyear'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='collected_from',
            field=models.ForeignKey(limit_choices_to={'account_level': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='collected_from_account', to='account.account'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='to_account',
            field=models.ForeignKey(limit_choices_to={'account_level': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='collected_to_account', to='account.account'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.transaction'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='from_account',
            field=models.ForeignKey(limit_choices_to={'account_level': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='paid_from_account', to='account.account'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='paid_to',
            field=models.ForeignKey(limit_choices_to={'account_level': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='paid_to_account', to='account.account'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.transaction'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(limit_choices_to={'account_level': 5}, on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='account.transaction'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='financial_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.financialyear'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreceiptvoucher',
            name='collected_from',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account'),
        ),
        migrations.AddField(
            model_name='historicalreceiptvoucher',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='historicalreceiptvoucher',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreceiptvoucher',
            name='to_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account'),
        ),
        migrations.AddField(
            model_name='historicalreceiptvoucher',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.transaction'),
        ),
        migrations.AddField(
            model_name='historicalpaymentvoucher',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='historicalpaymentvoucher',
            name='from_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account'),
        ),
        migrations.AddField(
            model_name='historicalpaymentvoucher',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpaymentvoucher',
            name='paid_to',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account'),
        ),
        migrations.AddField(
            model_name='historicalpaymentvoucher',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.transaction'),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.transaction'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='accountsettlementdebit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='accountsettlementdebit',
            name='debit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_account_settlement_debit', to='account.account'),
        ),
        migrations.AddField(
            model_name='accountsettlementdebit',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.transaction'),
        ),
        migrations.AddField(
            model_name='accountsettlementcredit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='accountsettlementcredit',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account_settlement_credit', to='account.account'),
        ),
        migrations.AddField(
            model_name='accountsettlementcredit',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.transaction'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='account.account'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'account_name_en')},
        ),
    ]
