# Generated by Django 4.2.4 on 2024-06-30 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('print_account_statement', 'Can Print Account Statement'), ('print_account_receipt_voucher', 'Can Print Account Receipt Voucher'), ('can_view_agent_account', 'Can View Agent Account'), ('can_view_transport_company_account', 'Can View Transport Company Account'), ('can_view_internal_account', 'Can View Internal Account'), ('can_view_accounts_tree', 'Can View Accounts Tree')], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountsettlementcredit',
            options={'verbose_name': 'Account Settlement Credit', 'verbose_name_plural': 'Account Settlement Credits'},
        ),
        migrations.AlterModelOptions(
            name='accountsettlementdebit',
            options={'verbose_name': 'Account Settlement Debit', 'verbose_name_plural': 'Account Settlement Debits'},
        ),
        migrations.AlterModelOptions(
            name='debitvoucher',
            options={'verbose_name': 'Debit Voucher', 'verbose_name_plural': 'Debit Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='receiptvoucher',
            options={'verbose_name': 'Receipt Voucher', 'verbose_name_plural': 'Receipt Vouchers'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name_ar',
            field=models.CharField(max_length=64, verbose_name='Account Name Arabic'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name_en',
            field=models.CharField(max_length=64, verbose_name='Account Name English'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('A', 'Asset'), ('L', 'Liability'), ('E', 'Equity'), ('R', 'Revenue'), ('X', 'Expense')], max_length=1, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='allow_child_accounts',
            field=models.BooleanField(default=False, verbose_name='Allow Child Accounts'),
        ),
        migrations.AlterField(
            model_name='accountsettlementcredit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='accountsettlementcredit',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='accountsettlementcredit',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accountsettlementcredit',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('settlement', 'Settlement')], default='settlement', max_length=16, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='accountsettlementdebit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='accountsettlementdebit',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='accountsettlementdebit',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accountsettlementdebit',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('settlement', 'Settlement')], default='settlement', max_length=16, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='date',
            field=models.DateField(blank=True, editable=False, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='HistoricalJournalEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Date')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Credit')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.transaction')),
            ],
            options={
                'verbose_name': 'historical Journal Entry',
                'verbose_name_plural': 'historical Journal Entries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
