# Generated by Django 4.2.4 on 2024-06-30 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('account', '0003_alter_account_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentVoucher',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('paid_to_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Paid To')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('referance_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Referance Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('from_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account')),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.transaction')),
            ],
            options={
                'verbose_name': 'historical Payment Voucher',
                'verbose_name_plural': 'historical Payment Vouchers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReceiptVoucher',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('collected_from_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Collected From')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('referance_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Referance Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('collected_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account')),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.transaction')),
            ],
            options={
                'verbose_name': 'historical Receipt Voucher',
                'verbose_name_plural': 'historical Receipt Vouchers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('paid_to_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Paid To')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('referance_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Referance Number')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit Card / Debit Card'), ('other', 'Other')], max_length=16, null=True, verbose_name='Payment Method')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_from_account', to='account.account')),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_to_account', to='account.account')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.transaction')),
            ],
            options={
                'verbose_name': 'Payment Voucher',
                'verbose_name_plural': 'Payment Vouchers',
            },
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='collected_from_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Collected From'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='collected_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_from_account', to='account.account'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_to_account', to='account.account'),
        ),
        migrations.DeleteModel(
            name='DebitVoucher',
        ),
    ]
