# Generated by Django 4.2.4 on 2024-07-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentvoucher',
            name='from_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentvoucher',
            name='paid_to',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account'),
        ),
        migrations.AlterField(
            model_name='historicalreceiptvoucher',
            name='collected_from',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account'),
        ),
        migrations.AlterField(
            model_name='historicalreceiptvoucher',
            name='to_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(limit_choices_to={'level': 5}, on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='from_account',
            field=models.ForeignKey(limit_choices_to={'level': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='paid_from_account', to='account.account'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='paid_to',
            field=models.ForeignKey(limit_choices_to={'level': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='paid_to_account', to='account.account'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='collected_from',
            field=models.ForeignKey(limit_choices_to={'level': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='collected_from_account', to='account.account'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='to_account',
            field=models.ForeignKey(limit_choices_to={'level': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='collected_to_account', to='account.account'),
        ),
    ]
