# Generated by Django 4.2.4 on 2024-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_historicaljournalentry_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='allow_child_accounts',
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, verbose_name='Account Level'),
        ),
    ]
