# Generated by Django 4.2.4 on 2024-06-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_historicalpaymentvoucher_historicalreceiptvoucher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsettlementcredit',
            old_name='referance_number',
            new_name='reference_no',
        ),
        migrations.RenameField(
            model_name='accountsettlementdebit',
            old_name='referance_number',
            new_name='reference_no',
        ),
        migrations.RenameField(
            model_name='historicalpaymentvoucher',
            old_name='referance_number',
            new_name='reference_no',
        ),
        migrations.RenameField(
            model_name='historicalreceiptvoucher',
            old_name='referance_number',
            new_name='reference_no',
        ),
        migrations.RenameField(
            model_name='paymentvoucher',
            old_name='referance_number',
            new_name='reference_no',
        ),
        migrations.RenameField(
            model_name='receiptvoucher',
            old_name='referance_number',
            new_name='reference_no',
        ),
    ]
