# Generated by Django 4.2.4 on 2024-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_referance_number_accountsettlementcredit_reference_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettlementcredit',
            name='reference_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='accountsettlementdebit',
            name='reference_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentvoucher',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentvoucher',
            name='reference_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='historicalreceiptvoucher',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalreceiptvoucher',
            name='reference_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='reference_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='reference_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference Number'),
        ),
    ]
