# Generated by Django 3.2.25 on 2024-07-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_allow_child_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettlementdebit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='accountsettlementdebit',
            name='debit_account',
        ),
        migrations.RemoveField(
            model_name='accountsettlementdebit',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='AccountSettlementCredit',
        ),
        migrations.DeleteModel(
            name='AccountSettlementDebit',
        ),
    ]
