# Generated by Django 3.2.25 on 2024-07-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20240720_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
