# Generated by Django 4.2.4 on 2024-07-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accountsettlementcredit_reference_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournalentry',
            name='entry_for',
            field=models.CharField(max_length=16, null=True, verbose_name='Entry For'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_for',
            field=models.CharField(max_length=16, null=True, verbose_name='Entry For'),
        ),
    ]
