# Generated by Django 4.2.4 on 2024-07-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_historicaljournalentry_entry_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='account.transaction'),
        ),
    ]
