# Generated by Django 4.2.4 on 2024-07-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_journalentry_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournalentry',
            name='description_ar',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Arabic'),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='description_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description English'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='description_ar',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Arabic'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='description_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description English'),
        ),
    ]
