# Generated by Django 4.2.4 on 2024-07-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_accountsettlementcredit_reference_no_and_more'),
        ('company', '0003_historicalsystemsettings_gib_main_account_and_more'),
        ('agent', '0002_alter_agent_agent_type_alter_agentcommission_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahVisaGroupInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(max_length=50, unique=True, verbose_name='Group No')),
                ('pax', models.IntegerField(verbose_name='Pax')),
                ('visa_sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Visa Price')),
                ('transport_included', models.BooleanField(default=False, verbose_name='Transport Included')),
                ('comission_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comission Rate')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='VAT Percentage')),
                ('ground_service_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ground Service Price')),
                ('visa_fees', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Visa Fee')),
                ('insurance_fees', models.DecimalField(decimal_places=2, default=64.85, max_digits=10, verbose_name='Insurance Fee')),
                ('electronic_services_fees', models.DecimalField(decimal_places=2, default=102.07, max_digits=10, verbose_name='Electronic Services Fee')),
                ('transport_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Transport BRN')),
                ('hotel_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Hotel BRN')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent', verbose_name='Agent')),
                ('comission_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comission_transaction', to='account.transaction', verbose_name='Comission Transaction')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
                ('visa_purchase_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_purchase_transaction', to='account.transaction', verbose_name='Visa Purchase Transaction')),
                ('visa_sale_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_sale_transaction', to='account.transaction', verbose_name='Visa Sale Transaction')),
            ],
        ),
    ]
