# Generated by Django 4.2.4 on 2024-07-11 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0002_initial'),
        ('agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahVisaGroupInvoiceDefaultPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_service_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ground Service Price')),
                ('visa_fees', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Visa Fee')),
                ('insurance_fees', models.DecimalField(decimal_places=2, default=64.85, max_digits=10, verbose_name='Insurance Fee')),
                ('electronic_services_fees', models.DecimalField(decimal_places=2, default=102.07, max_digits=10, verbose_name='Electronic Services Fee')),
                ('transport_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Transport BRN')),
                ('hotel_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Hotel BRN')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahVisaGroupInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('group_no', models.CharField(max_length=50, unique=True, verbose_name='Group No')),
                ('voucher_no', models.CharField(max_length=50, unique=True, verbose_name='Voucher No')),
                ('pax', models.IntegerField(default=1, verbose_name='PAX')),
                ('visa_sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Visa Price')),
                ('transport_included', models.BooleanField(default=False, verbose_name='Transport Included')),
                ('comission_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comission Rate')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='VAT Percentage')),
                ('ground_service_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ground Service Price')),
                ('visa_fees', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Visa Fee')),
                ('insurance_fees', models.DecimalField(decimal_places=2, default=64.85, max_digits=10, verbose_name='Insurance Fee')),
                ('electronic_services_fees', models.DecimalField(decimal_places=2, default=102.07, max_digits=10, verbose_name='Electronic Services Fee')),
                ('transport_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Transport BRN')),
                ('hotel_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Hotel BRN')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent', verbose_name='Agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transaction', verbose_name='Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUmrahVisaGroupInvoiceDefaultPrices',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ground_service_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ground Service Price')),
                ('visa_fees', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Visa Fee')),
                ('insurance_fees', models.DecimalField(decimal_places=2, default=64.85, max_digits=10, verbose_name='Insurance Fee')),
                ('electronic_services_fees', models.DecimalField(decimal_places=2, default=102.07, max_digits=10, verbose_name='Electronic Services Fee')),
                ('transport_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Transport BRN')),
                ('hotel_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Hotel BRN')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical umrah visa group invoice default prices',
                'verbose_name_plural': 'historical umrah visa group invoice default pricess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUmrahVisaGroupInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('group_no', models.CharField(db_index=True, max_length=50, verbose_name='Group No')),
                ('voucher_no', models.CharField(db_index=True, max_length=50, verbose_name='Voucher No')),
                ('pax', models.IntegerField(default=1, verbose_name='PAX')),
                ('visa_sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Visa Price')),
                ('transport_included', models.BooleanField(default=False, verbose_name='Transport Included')),
                ('comission_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comission Rate')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='VAT Percentage')),
                ('ground_service_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ground Service Price')),
                ('visa_fees', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Visa Fee')),
                ('insurance_fees', models.DecimalField(decimal_places=2, default=64.85, max_digits=10, verbose_name='Insurance Fee')),
                ('electronic_services_fees', models.DecimalField(decimal_places=2, default=102.07, max_digits=10, verbose_name='Electronic Services Fee')),
                ('transport_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Transport BRN')),
                ('hotel_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Hotel BRN')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.agent', verbose_name='Agent')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'historical umrah visa group invoice',
                'verbose_name_plural': 'historical umrah visa group invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
