# Generated by Django 4.2.4 on 2024-07-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accountsettlementcredit_reference_no_and_more'),
        ('visa_group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umrahvisagroupinvoice',
            name='comission_transaction',
        ),
        migrations.RemoveField(
            model_name='umrahvisagroupinvoice',
            name='visa_purchase_transaction',
        ),
        migrations.RemoveField(
            model_name='umrahvisagroupinvoice',
            name='visa_sale_transaction',
        ),
        migrations.AddField(
            model_name='umrahvisagroupinvoice',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transaction', verbose_name='Transaction'),
        ),
    ]
