# Generated by Django 4.2.4 on 2024-07-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_historicalsystemsettings_vat_payable_account_and_more'),
        ('visa_group', '0002_remove_umrahvisagroupinvoice_comission_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahVisaGroupInvoiceDefaultPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_service_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ground Service Price')),
                ('visa_fees', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Visa Fee')),
                ('insurance_fees', models.DecimalField(decimal_places=2, default=64.85, max_digits=10, verbose_name='Insurance Fee')),
                ('electronic_services_fees', models.DecimalField(decimal_places=2, default=102.07, max_digits=10, verbose_name='Electronic Services Fee')),
                ('transport_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Transport BRN')),
                ('hotel_brn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Hotel BRN')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
            ],
        ),
    ]
