# Generated by Django 4.2.4 on 2024-07-06 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visa_group', '0004_historicalumrahvisagroupinvoicedefaultprices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalumrahvisagroupinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
        migrations.AddField(
            model_name='umrahvisagroupinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
    ]
