# Generated by Django 4.2.4 on 2024-07-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_group', '0005_historicalumrahvisagroupinvoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalumrahvisagroupinvoice',
            name='voucher_no',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Voucher No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='umrahvisagroupinvoice',
            name='voucher_no',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Voucher No'),
            preserve_default=False,
        ),
    ]
