# Generated by Django 4.2.4 on 2024-07-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_group', '0006_historicalumrahvisagroupinvoice_voucher_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalumrahvisagroupinvoice',
            name='pax',
            field=models.IntegerField(default=1, verbose_name='Pax'),
        ),
        migrations.AlterField(
            model_name='umrahvisagroupinvoice',
            name='pax',
            field=models.IntegerField(default=1, verbose_name='Pax'),
        ),
    ]
