# Generated by Django 4.2.4 on 2024-07-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_group', '0007_alter_historicalumrahvisagroupinvoice_pax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalumrahvisagroupinvoice',
            name='pax',
            field=models.IntegerField(default=1, verbose_name='PAX'),
        ),
        migrations.AlterField(
            model_name='umrahvisagroupinvoice',
            name='pax',
            field=models.IntegerField(default=1, verbose_name='PAX'),
        ),
    ]
