# Generated by Django 4.2.4 on 2024-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpaymenttransaction',
            name='document_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference No'),
        ),
        migrations.AlterField(
            model_name='historicalagentpaymenttransaction',
            name='document_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reference No'),
        ),
    ]
