# Generated by Django 4.2.4 on 2024-07-11 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Code')),
                ('agent_type', models.CharField(choices=[('external', 'External Agent'), ('virtual', 'Virtual Agent')], max_length=16, verbose_name='Agent type')),
                ('name_en', models.CharField(max_length=64, verbose_name='Agent Name English')),
                ('name_ar', models.CharField(max_length=64, verbose_name='Agent Name Arabic')),
                ('address', models.TextField(max_length=256, verbose_name='Agent Address')),
                ('contact', models.TextField(max_length=256, verbose_name='Agent contact')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Token')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.account', verbose_name='Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country', verbose_name='Country')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAgentPrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Change Date')),
                ('visa_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visa Price')),
                ('visa_included_transport_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visa Included Transport Price')),
                ('transport_included_by_default', models.BooleanField(default=False, verbose_name='Transport Included By Default')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.agent', verbose_name='Agent')),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical agent price',
                'verbose_name_plural': 'historical agent prices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAgentCommission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Change Date')),
                ('commission_per_visa_with_transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Per Visa With Transport')),
                ('commission_per_visa_without_transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Per Visa Without Transport')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.agent', verbose_name='Agent')),
                ('comission_holder_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Comission Holder Account')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical agent commission',
                'verbose_name_plural': 'historical agent commissions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAgent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Code')),
                ('agent_type', models.CharField(choices=[('external', 'External Agent'), ('virtual', 'Virtual Agent')], max_length=16, verbose_name='Agent type')),
                ('name_en', models.CharField(max_length=64, verbose_name='Agent Name English')),
                ('name_ar', models.CharField(max_length=64, verbose_name='Agent Name Arabic')),
                ('address', models.TextField(max_length=256, verbose_name='Agent Address')),
                ('contact', models.TextField(max_length=256, verbose_name='Agent contact')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Token')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Account')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company')),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country', verbose_name='Country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical agent',
                'verbose_name_plural': 'historical agents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AgentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Change Date')),
                ('visa_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visa Price')),
                ('visa_included_transport_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visa Included Transport Price')),
                ('transport_included_by_default', models.BooleanField(default=False, verbose_name='Transport Included By Default')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent.agent', verbose_name='Agent')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Change Date')),
                ('commission_per_visa_with_transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Per Visa With Transport')),
                ('commission_per_visa_without_transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Per Visa Without Transport')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='agent.agent', verbose_name='Agent')),
                ('comission_holder_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.account', verbose_name='Comission Holder Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('nusuk', 'Nusuk'), ('tawaf', 'Tawaf'), ('waytoumrah', 'Way to Umrah'), ('babalumrah', 'Baba Al Umrah')], default='nusuk', max_length=64, verbose_name='Platform')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent.agent', verbose_name='Agent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country', verbose_name='Country')),
            ],
        ),
    ]
