# Generated by Django 4.2.4 on 2024-07-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('external', 'External Agent'), ('virtual', 'Virtual Agent')], max_length=16, verbose_name='Agent type'),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='agent.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='agent_type',
            field=models.CharField(choices=[('external', 'External Agent'), ('virtual', 'Virtual Agent')], max_length=16, verbose_name='Agent type'),
        ),
    ]
