# Generated by Django 3.2.25 on 2024-07-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_allow_child_accounts_and_more'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'A', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'A', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Account'),
        ),
    ]
