# Generated by Django 4.2.4 on 2024-07-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_agent_type_alter_agentcommission_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprice',
            name='is_group_transport_price',
        ),
        migrations.RemoveField(
            model_name='agentprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='agentprice',
            name='transport_price',
        ),
        migrations.RemoveField(
            model_name='historicalagentprice',
            name='is_group_transport_price',
        ),
        migrations.RemoveField(
            model_name='historicalagentprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='historicalagentprice',
            name='transport_price',
        ),
        migrations.AddField(
            model_name='agentprice',
            name='visa_included_transport_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visa Included Transport Price'),
        ),
        migrations.AddField(
            model_name='agentprice',
            name='visa_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visa Price'),
        ),
        migrations.AddField(
            model_name='historicalagentprice',
            name='visa_included_transport_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visa Included Transport Price'),
        ),
        migrations.AddField(
            model_name='historicalagentprice',
            name='visa_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visa Price'),
        ),
    ]
