# Generated by Django 3.2.25 on 2024-07-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20240713_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_view_account_statement',
            field=models.BooleanField(default=False, verbose_name='Can View Account Statement'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='can_view_account_statement',
            field=models.BooleanField(default=False, verbose_name='Can View Account Statement'),
        ),
    ]
