# Generated by Django 4.2.4 on 2024-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_agentprice_is_group_transport_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprice',
            name='transport_included_by_default',
            field=models.BooleanField(default=False, verbose_name='Transport Included By Default'),
        ),
        migrations.AddField(
            model_name='historicalagentprice',
            name='transport_included_by_default',
            field=models.BooleanField(default=False, verbose_name='Transport Included By Default'),
        ),
    ]
