# Generated by Django 4.2.4 on 2024-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='delete_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Delete Hours'),
        ),
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='edit_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Edit Hours'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='delete_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Delete Hours'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='edit_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Edit Hours'),
        ),
    ]
