# Generated by Django 4.2.4 on 2024-07-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_allow_child_accounts_and_more'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='agent_account_tree',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'A', 'level': 4}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Agent Account Tree'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='agent_commission_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'L', 'level': 4}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Agent Commission Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='gib_main_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'A', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='GIB Main Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='gib_virtual_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'A', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='GIB Virtual Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='transport_company_account_tree',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'L', 'level': 4}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Transport Company Account Tree'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='transport_expense_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'X', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Transport Expense Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='transport_purchase_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'X', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Transport Purchase Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='transport_sales_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'R', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Transport Sales Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='umrah_visa_purchase_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'X', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Umrah Visa Purchase Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='umrah_visa_sales_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'R', 'level': 4}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Umrah Visa Sales Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='vat_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'L', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='VAT Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='agent_account_tree',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'A', 'level': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_account_tree', to='account.account', verbose_name='Agent Account Tree'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='agent_commission_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'L', 'level': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_commission_account', to='account.account', verbose_name='Agent Commission Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='gib_main_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'A', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gib_main_account', to='account.account', verbose_name='GIB Main Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='gib_virtual_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'A', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gib_virtual_account', to='account.account', verbose_name='GIB Virtual Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='transport_company_account_tree',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'L', 'level': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_company_account_tree', to='account.account', verbose_name='Transport Company Account Tree'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='transport_expense_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'X', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_expense_account', to='account.account', verbose_name='Transport Expense Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='transport_purchase_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'X', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_purchase_account', to='account.account', verbose_name='Transport Purchase Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='transport_sales_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'R', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_sales_account', to='account.account', verbose_name='Transport Sales Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='umrah_visa_purchase_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'X', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='umrah_visa_purchase_account', to='account.account', verbose_name='Umrah Visa Purchase Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='umrah_visa_sales_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'R', 'level': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='umrah_visa_sales_account', to='account.account', verbose_name='Umrah Visa Sales Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='vat_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'L', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_account', to='account.account', verbose_name='VAT Account'),
        ),
    ]
