# Generated by Django 4.2.4 on 2024-07-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accountsettlementcredit_reference_no_and_more'),
        ('company', '0002_historicalsystemsettings_delete_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='gib_main_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='GIB Main Account'),
        ),
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='gib_virtual_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='GIB Virtual Account'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gib_main_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gib_main_account', to='account.account', verbose_name='GIB Main Account'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gib_virtual_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gib_virtual_account', to='account.account', verbose_name='GIB Virtual Account'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='company.company', unique=True, verbose_name='Company'),
        ),
    ]
