# Generated by Django 4.2.4 on 2024-07-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_allow_child_accounts_and_more'),
        ('company', '0002_alter_historicalsystemsettings_agent_account_tree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsystemsettings',
            name='agent_account_tree',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='agent_account_tree',
        ),
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='external_agents_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'A', 'level': 4}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='External Agents Account'),
        ),
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='virtual_agents_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'A', 'level': 4}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Virtual Agents Account'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='external_agents_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'A', 'level': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_agents_account', to='account.account', verbose_name='External Agents Account'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='virtual_agents_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'A', 'level': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_agents_account', to='account.account', verbose_name='Virtual Agents Account'),
        ),
    ]
