# Generated by Django 3.2.25 on 2024-07-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_allow_child_accounts_and_more'),
        ('company', '0003_remove_historicalsystemsettings_agent_account_tree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='default_currency',
            field=models.CharField(choices=[('SAR', 'SAR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AED', 'AED'), ('INR', 'INR'), ('PKR', 'PKR'), ('EGP', 'EGP'), ('BHD', 'BHD'), ('KWD', 'KWD'), ('QAR', 'QAR'), ('OMR', 'OMR'), ('JOD', 'JOD'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('CHF', 'CHF'), ('MYR', 'MYR'), ('SGD', 'SGD'), ('THB', 'THB'), ('IDR', 'IDR'), ('PHP', 'PHP'), ('LKR', 'LKR'), ('BDT', 'BDT'), ('NPR', 'NPR'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('KRW', 'KRW'), ('TRY', 'TRY'), ('RUB', 'RUB'), ('ZAR', 'ZAR'), ('NGN', 'NGN'), ('MXN', 'MXN'), ('BRL', 'BRL'), ('PLN', 'PLN'), ('ILS', 'ILS'), ('NZD', 'NZD'), ('SEK', 'SEK'), ('DKK', 'DKK'), ('NOK', 'NOK'), ('HUF', 'HUF'), ('CZK', 'CZK'), ('RON', 'RON'), ('COP', 'COP'), ('CLP', 'CLP'), ('PEN', 'PEN'), ('ARS', 'ARS'), ('VND', 'VND'), ('UAH', 'UAH'), ('MAD', 'MAD'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('BDT', 'BDT'), ('KES', 'KES'), ('GHS', 'GHS'), ('XAF', 'XAF'), ('XOF', 'XOF'), ('TZS', 'TZS'), ('DZD', 'DZD')], default='SAR', max_length=3, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='historicalsystemsettings',
            name='umrah_visa_sales_account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'R', 'level': 5}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='Umrah Visa Sales Account'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_currency',
            field=models.CharField(choices=[('SAR', 'SAR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AED', 'AED'), ('INR', 'INR'), ('PKR', 'PKR'), ('EGP', 'EGP'), ('BHD', 'BHD'), ('KWD', 'KWD'), ('QAR', 'QAR'), ('OMR', 'OMR'), ('JOD', 'JOD'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('CHF', 'CHF'), ('MYR', 'MYR'), ('SGD', 'SGD'), ('THB', 'THB'), ('IDR', 'IDR'), ('PHP', 'PHP'), ('LKR', 'LKR'), ('BDT', 'BDT'), ('NPR', 'NPR'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('KRW', 'KRW'), ('TRY', 'TRY'), ('RUB', 'RUB'), ('ZAR', 'ZAR'), ('NGN', 'NGN'), ('MXN', 'MXN'), ('BRL', 'BRL'), ('PLN', 'PLN'), ('ILS', 'ILS'), ('NZD', 'NZD'), ('SEK', 'SEK'), ('DKK', 'DKK'), ('NOK', 'NOK'), ('HUF', 'HUF'), ('CZK', 'CZK'), ('RON', 'RON'), ('COP', 'COP'), ('CLP', 'CLP'), ('PEN', 'PEN'), ('ARS', 'ARS'), ('VND', 'VND'), ('UAH', 'UAH'), ('MAD', 'MAD'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('BDT', 'BDT'), ('KES', 'KES'), ('GHS', 'GHS'), ('XAF', 'XAF'), ('XOF', 'XOF'), ('TZS', 'TZS'), ('DZD', 'DZD')], default='SAR', max_length=3, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='umrah_visa_sales_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'R', 'level': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='umrah_visa_sales_account', to='account.account', verbose_name='Umrah Visa Sales Account'),
        ),
    ]
