# Generated by Django 4.2.4 on 2024-07-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accountsettlementcredit_reference_no_and_more'),
        ('company', '0003_historicalsystemsettings_gib_main_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsystemsettings',
            name='vat_payable_account',
        ),
        migrations.RemoveField(
            model_name='historicalsystemsettings',
            name='vat_receivable_account',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vat_payable_account',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vat_receivable_account',
        ),
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='vat_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', verbose_name='VAT Account'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vat_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_account', to='account.account', verbose_name='VAT Account'),
        ),
    ]
