# Generated by Django 4.2.4 on 2024-07-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_historicalsystemsettings_vat_payable_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemsettings',
            name='account_statement_note',
            field=models.TextField(blank=True, null=True, verbose_name='Account Statement Note'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='account_statement_note',
            field=models.TextField(blank=True, null=True, verbose_name='Account Statement Note'),
        ),
    ]
