# Generated by Django 3.2.25 on 2024-07-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20240719_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='schedule_screen_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Schedule Screen Key'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='schedule_screen_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Schedule Screen Key'),
        ),
    ]
