# Generated by Django 4.2.4 on 2024-07-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_historicalsystemsettings_account_statement_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='company.company', verbose_name='Company'),
        ),
    ]
