# Generated by Django 4.2.4 on 2024-06-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name')),
                ('cr_no', models.CharField(max_length=255, verbose_name='CR No')),
                ('vat_no', models.CharField(max_length=255, verbose_name='VAT No')),
                ('vat_percentage', models.FloatField(default=15, verbose_name='VAT Percentage')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('is_transport_company', models.BooleanField(default=False, verbose_name='Is Transport Company')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Supplier',
                'verbose_name_plural': 'historical Suppliers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name')),
                ('cr_no', models.CharField(max_length=255, verbose_name='CR No')),
                ('vat_no', models.CharField(max_length=255, verbose_name='VAT No')),
                ('vat_percentage', models.FloatField(default=15, verbose_name='VAT Percentage')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('is_transport_company', models.BooleanField(default=False, verbose_name='Is Transport Company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ('name_en', 'name_ar', 'company'),
                'unique_together': {('name_en', 'name_ar', 'company')},
            },
        ),
    ]
