"""
Django settings for umrahpro project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from django.contrib.messages import constants as messages
import os

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8)#yt5=)x7rypvopu9ln)9(^mnsnxs2jx0(a75ygh==h!+%y@a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Application definition


INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dbbackup',
    'crispy_forms',
    'ajax_datatable',
    'simple_history',
    'django_filters',
    'arrival_voucher',
    'django_tables2',
    # 'service_order',  
    'core',
    'company',
    'agent',
    'voucher',
    'payment',
    'transport',
    'supplier',
    'account',
    'invoice',
    'mandoob', # Mandoob (Field Officer) will this app only
    'visa_group',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
    'simple_history.middleware.HistoryRequestMiddleware',
    

]

ROOT_URLCONF = 'umrahflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'django_auto_logout.context_processors.auto_logout_client',

                'core.context_processors.account_names',


            ],
        },
    },
]

WSGI_APPLICATION = 'umrahflow.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'HBNmughal$umrahflow',
            'USER': 'HBNmughal',
            'PASSWORD': 'Hm369903',
            'HOST': 'hbnmughal.mysql.pythonanywhere-services.com',
            'PORT': "",
            # "OPTIONS": {
            # "init_command": "SET sql_mode='STRICT_TRANS_TABLES', innodb_strict_mode=1",
        # },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True


USE_TZ = True

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
if DEBUG:
    DBBACKUP_STORAGE_OPTIONS = {'location': BASE_DIR/'dB_backups'}
else:
    DBBACKUP_STORAGE_OPTIONS = {'location': '/home/HBNmughal/umrahflow/dB_backups'}


LANGUAGES = (
    ('en', _('English')),
    ('ar', _('Arabic')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


LOCALE_PATHS = [
    BASE_DIR / 'locale/',

    '/var/www/locale/',

]
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'info',
        messages.SUCCESS: 'success',
        messages.WARNING: 'warning',
        messages.ERROR: 'error',
 }

LOGIN_URL = 'login'

if DEBUG == False:
    _TOUT = 1800
else:
    _TOUT = 3000


AUTO_LOGOUT = {
    'IDLE_TIME': _TOUT,
    'MESSAGE': _('The session has expired. Please login again to continue.'),
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,

}

MEDIA_ROOT =  BASE_DIR/ 'media'
MEDIA_URL = '/media/'

# DATE_INPUT_FORMATS = ['%d-%m-%Y']

CRISPY_TEMPLATE_PACK = 'bootstrap3'


USE_L10N = False
USE_THOUSAND_SEPARATOR = False
DECIMAL_SEPARATOR = '.'
THOUSAND_SEPARATOR = ','
DATE_FORMAT = 'd/m/Y'


VAT_PERCENTAGE = 15.00