# Generated by Django 4.2.4 on 2024-06-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandoob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('city', models.CharField(choices=[('makkah', 'Makkah'), ('madinah', 'Medina'), ('medina_airport', 'Medina Airport'), ('jeddah_airport', 'Jeddah Airport')], max_length=20, verbose_name='City')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Token')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Mandoob',
                'verbose_name_plural': 'Mandoobs',
                'permissions': (('view_jeddah_airport_schedule', 'View Jeddah Airport Schedule'), ('view_medina_airport_schedule', 'View Medina Airport Schedule'), ('view_makkah_schedule', 'View Makkah Schedule'), ('view_madinah_schedule', 'View Madinah Schedule'), ('can_update_group_leader', 'Can Update Group Leader'), ('can_update_makkah_hotel', 'Can Update Makkah Hotel'), ('can_update_madinah_hotel', 'Can Update Madinah Hotel'), ('can_mark_as_completed', 'Can Mark As Completed'), ('can_mark_as_on_the_way', 'Can Mark As On The Way')),
            },
        ),
    ]
