# Generated by Django 4.2.4 on 2024-07-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0002_initial'),
        ('arrival_voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('invoice_no', models.CharField(max_length=256, verbose_name='Invoice No')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('vat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='VAT Percentage')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='VAT Amount')),
                ('additional_movement', models.BooleanField(blank=True, default=False, null=True, verbose_name='Additional Movement')),
                ('arrival_voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arrival_voucher.arrivalvoucher')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('expense_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entry', to='account.journalentry', verbose_name='Expense Entry')),
            ],
            options={
                'verbose_name': 'Transport Purchase Invoice',
                'verbose_name_plural': 'Transport Purchase Invoices',
            },
        ),
    ]
