# Generated by Django 4.2.4 on 2024-06-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('account', '0002_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportpurchaseinvoice',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_movement', to='transport.transportmovement'),
        ),
        migrations.AddField(
            model_name='transportpurchaseinvoice',
            name='supplier_entry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_entry', to='account.journalentry', verbose_name='Supplier Entry'),
        ),
        migrations.AddField(
            model_name='transportpurchaseinvoice',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transaction'),
        ),
        migrations.AddField(
            model_name='transportpurchaseinvoice',
            name='transport_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.transportcompany'),
        ),
    ]
