# Generated by Django 4.2.4 on 2024-07-11 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('agent', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_referance_no', models.CharField(blank=True, max_length=256, null=True, verbose_name='Agent Reference No')),
                ('group_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Group name')),
                ('group_no', models.CharField(max_length=256, verbose_name='Group no')),
                ('pax', models.IntegerField(verbose_name='PAX')),
                ('group_leader', models.CharField(blank=True, max_length=32, null=True, verbose_name='Group leader name')),
                ('group_leader_contact', models.CharField(blank=True, max_length=32, null=True, verbose_name='Group leader contact')),
                ('transport_brn', models.CharField(blank=True, max_length=256, null=True, verbose_name='Transport BRN')),
                ('transportation_type', models.CharField(blank=True, choices=[('air', 'By Air'), ('land', 'By Land'), ('sea', 'By Sea')], max_length=32, null=True, verbose_name='Transportation Type')),
                ('arrival_flight_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='Arrival Flight No')),
                ('arrival_airport', models.CharField(blank=True, choices=[('JED', 'Jeddah Airport'), ('MED', 'Medina Airport')], max_length=32, null=True, verbose_name='Arrival Airport')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Arrival Date')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('departure_flight_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='Departure Flight No')),
                ('departure_airport', models.CharField(blank=True, choices=[('JED', 'Jeddah Airport'), ('MED', 'Medina Airport')], max_length=32, null=True, verbose_name='Departure Airport')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Departure Date')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('makkah_hotel', models.CharField(blank=True, max_length=64, null=True, verbose_name='Makkah Hotel')),
                ('medina_hotel', models.CharField(blank=True, max_length=64, null=True, verbose_name='Medina Hotel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Transport'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('with_agent_draft', 'Draft, with agent'), ('with_agent_rejected', 'Rejected, sent back to agent')], default='draft', max_length=32, verbose_name='Status')),
                ('rejected_reason', models.TextField(blank=True, null=True, verbose_name='Rejected Reason')),
                ('rawdah_men_request_date', models.DateField(blank=True, null=True, verbose_name='Men Request Date')),
                ('rawdah_women_request_date', models.DateField(blank=True, null=True, verbose_name='Women Request Date')),
                ('rawdah_men_reservation_date', models.DateField(blank=True, null=True, verbose_name='Men Reservation Date')),
                ('rawdah_men_reservation_time', models.TimeField(blank=True, null=True, verbose_name='Men Reservation Time')),
                ('rawdah_men_status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('completed', 'Completed'), ('not_available', 'Not Available')], default='pending', max_length=32, verbose_name='Men Status')),
                ('rawdah_women_reservation_date', models.DateField(blank=True, null=True, verbose_name='Women Reservation Date')),
                ('rawdah_women_reservation_time', models.TimeField(blank=True, null=True, verbose_name='Women Reservation Time')),
                ('rawdah_women_status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('completed', 'Completed'), ('not_available', 'Not Available')], default='pending', max_length=32, verbose_name='Women Status')),
                ('transport_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Transport'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='draft', max_length=32, verbose_name='Transport Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('package_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Package Purchase Amount')),
                ('package_sale_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Package Sale Amount')),
                ('voucher_remarks', models.TextField(blank=True, null=True, verbose_name='Voucher Remarks')),
                ('transport_remarks', models.TextField(blank=True, null=True, verbose_name='Transport Remarks')),
                ('remarks_for_accounts', models.TextField(blank=True, null=True, verbose_name='Remarks for Accounts')),
                ('accounts_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('query', 'Query'), ('updated_pending', 'Updated, Pending Approval')], default='draft', max_length=32, verbose_name='Accounts Status')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent.agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.country', verbose_name='Country')),
            ],
            options={
                'permissions': (('can_add_extra_movement', 'Can add extra movement'), ('can_delete_movement', 'Can delete movement'), ('can_change_movement_date', 'Can change movement date'), ('can_change_movement_status_after_completed', 'Can change movement status after completed'), ('can_view_arrival_voucher_invoice', 'Can view arrival voucher invoice')),
            },
        ),
        migrations.CreateModel(
            name='ArrivalVoucherGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrival_voucher.arrivalvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalVoucherChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrival_voucher.arrivalvoucher')),
            ],
        ),
    ]
