# Generated by Django 4.2.4 on 2024-06-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        ('arrival_voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalvoucher',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.transportpurchaseinvoice', verbose_name='Purchase Invoice'),
        ),
    ]
