# Generated by Django 4.2.4 on 2024-06-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('voucher', '0001_initial'),
        ('arrival_voucher', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalvoucher',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='voucher.transportinvoice'),
        ),
        migrations.AddField(
            model_name='arrivalvoucher',
            name='transport_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.transportcompany', verbose_name='Transport company'),
        ),
        migrations.AddField(
            model_name='arrivalvoucher',
            name='transport_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.transportpackage', verbose_name='Transport Package'),
        ),
        migrations.AddField(
            model_name='arrivalvoucher',
            name='transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.transporttype', verbose_name='Transport Type'),
        ),
    ]
