# Generated by Django 4.2.4 on 2024-06-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('arrival_voucher', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalvouchergroups',
            name='agent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrivalvouchergroups',
            name='pax',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
