# Generated by Django 3.2.25 on 2024-07-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20240713_1657'),
        ('arrival_voucher', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalvoucher',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agent.agent', verbose_name='Agent'),
        ),
    ]
