# Generated by Django 4.2.4 on 2024-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival_voucher', '0004_arrivalvouchergroups_agent_arrivalvouchergroups_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalvoucher',
            name='agent_referance_no',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Agent Reference No'),
        ),
    ]
